spring.application.name=backend


# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

# C?u hình Hibernate (t? ??ng t?o b?ng t? code Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=jSsv9epHoWjMBJbMu7Pes4BTxYsROP/bcb+qdIr+loQ=
jwt.access-token-expiration=3h
jwt.refresh-token-expiration=7d